name: Fresh Entertainments
favicon: null
layout_spectrum: 0.46329
typography_spectrum: 0.8301836340688169
title: Fresh Entertainments
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#ed4898'
    - '#00b4d1'
    - '#f493c2'
    - '#343d30'
  brandStrength: 0.8961775361094624
  lightness: 0.8351460895501077
  saturation: 0.8369744983501732
  rhythmicContrast: 0.9999859109520912
purpose: []
